version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=spacesdb
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "spacesdb:/var/lib/postgresql/data"
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./spaces:/app"
    env_file:
      - .env
    ports:
      - "8100:8000"
    depends_on:
      - db
      - redis
      
  celery:
    build: .
    command: celery -A spaces worker -l info
    volumes:
      - "celerydata:/celery"
    env_file:
      - .env
    depends_on:
      - db
      - redis


  celery-beat:
    build: .
    command: celery -A spaces beat -l info
    volumes:
      - "celerybeatdata:/celerybeat"
    env_file:
      - .env        
    depends_on: 
      - db
      - redis
    

volumes:
  spacesdb:
  redisdata:
  celerydata:
  celerybeatdata:

