# Generated by Django 3.0 on 2020-03-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200320_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='updated_at',
        ),
    ]
