# Generated by Django 3.0 on 2020-03-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200320_1442'),
        ('api', '0005_auto_20200320_1015'),
    ]

    operations = [
    ]
