# Generated by Django 3.0 on 2020-03-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20200321_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='id',
            new_name='agent_id',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='id',
            new_name='space_id',
        ),
        migrations.RenameField(
            model_name='spacecategory',
            old_name='id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
