# Generated by Django 3.0 on 2020-03-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200326_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='number_of_bookings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
