# Generated by Django 3.0 on 2020-03-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200328_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='order_type',
        ),
        migrations.RenameField(
            model_name='ordertype',
            old_name='id',
            new_name='order_type_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='id',
            new_name='rating_id',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='id',
            new_name='refund_id',
        ),
    ]
