# Generated by Django 3.0 on 2020-03-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200329_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='orders_id',
        ),
    ]
