# Generated by Django 3.0 on 2020-04-10 17:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='space',
            name='availabilty',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Booked', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(default='12345abc', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='facilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['Rest room', 'Air conditioner'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['A sample url', 'Another url'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['No smoking', 'No drinking'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['A sampple url', 'Another url'], size=None),
            preserve_default=False,
        ),
    ]
