# Generated by Django 3.0 on 2020-04-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200410_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='space',
            name='images',
        ),
        migrations.RemoveField(
            model_name='space',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='space',
            name='videos',
        ),
        migrations.AddField(
            model_name='space',
            name='availabilty',
            field=models.BooleanField(default=True),
        ),
    ]
