# Generated by Django 3.0 on 2020-04-10 19:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200410_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='availabilty',
        ),
        migrations.AddField(
            model_name='space',
            name='facilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['Rest room'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['An image'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['No drinking'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['No videos'], size=None),
            preserve_default=False,
        ),
    ]
