# Generated by Django 3.0 on 2020-04-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200412_0737'),
        ('api', '0015_auto_20200410_2346'),
    ]

    operations = [
    ]
