# Generated by Django 3.0 on 2020-04-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200418_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='usage_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='usage_start_date',
            field=models.DateField(),
        ),
    ]
