# Generated by Django 3.0 on 2020-05-15 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200418_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='cancellation_rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), null=True, size=None),
        ),
        migrations.AddField(
            model_name='space',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='order_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
