# Generated by Django 3.0 on 2020-05-24 22:12

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200515_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='availability',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{'all_day': True, 'closing_time': '5pm', 'day': 'monday', 'opening_time': '8am'}], encoder=django.core.serializers.json.DjangoJSONEncoder),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='capacity',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='cancellation_rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=['50% refund only'], size=None),
            preserve_default=False,
        ),
    ]
