# Generated by Django 3.0 on 2020-06-12 02:33

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200524_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=50)),
                ('all_day', models.TextField()),
                ('open_time', models.CharField(max_length=50)),
                ('close_time', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('extra_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='space',
            old_name='facilities',
            new_name='amenities',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='availability',
            new_name='gmap',
        ),
        migrations.RemoveField(
            model_name='space',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='space',
            name='longitude',
        ),
        migrations.AddField(
            model_name='space',
            name='carspace',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='duration',
            field=models.CharField(default='daily', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.AddField(
            model_name='extra',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Space'),
        ),
        migrations.AddField(
            model_name='availability',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Space'),
        ),
    ]
