# Generated by Django 3.0 on 2020-06-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200612_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='location',
            new_name='address',
        ),
    ]
