# Generated by Django 3.0 on 2020-06-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200612_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='all_day',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='open_time',
            field=models.TimeField(null=True),
        ),
    ]
