# Generated by Django 3.0 on 2020-06-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200612_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='space',
        ),
    ]
