# Generated by Django 3.0 on 2020-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_availability_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='space',
            field=models.CharField(default='space', max_length=50),
            preserve_default=False,
        ),
    ]
