# Generated by Django 3.0 on 2020-06-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_availability_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='space',
            field=models.CharField(max_length=50),
        ),
    ]
