# Generated by Django 3.0 on 2020-06-17 07:39

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200616_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='noOfGuests',
            new_name='no_of_guest',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='company_email',
            field=models.CharField(default='one@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.CreateModel(
            name='OrderExtra',
            fields=[
                ('extra_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
            ],
        ),
    ]
