# Generated by Django 3.0 on 2020-06-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200617_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='usage_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='usage_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
