# Generated by Django 3.0 on 2020-06-18 16:45

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200618_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hours_booked',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
