# Generated by Django 3.0 on 2020-06-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_order_hours_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='videos',
        ),
        migrations.AlterField(
            model_name='availability',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Space'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Space'),
        ),
        migrations.AlterField(
            model_name='space',
            name='number_of_bookings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
