# Generated by Django 3.0 on 2020-06-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200621_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='space',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='extra',
            name='space',
            field=models.CharField(default='adedwe', max_length=50),
            preserve_default=False,
        ),
    ]
