# Generated by Django 3.0 on 2020-07-02 09:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200621_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='spacecategory',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='availability',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Space'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Space'),
        ),
        migrations.AlterField(
            model_name='space',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
