# Generated by Django 3.0 on 2020-07-10 20:10

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200624_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='days_booked',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
