# Generated by Django 3.0 on 2020-07-26 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_order_days_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('space_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('space_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SpaceCategory')),
            ],
        ),
    ]
