# Generated by Django 3.0 on 2020-08-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200801_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
