# Generated by Django 3.0 on 2020-08-23 13:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_order_expiry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('favorite_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
