# Generated by Django 3.0 on 2020-08-24 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200824_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Space'),
        ),
    ]
