# Generated by Django 3.0 on 2020-08-31 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20200824_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
