# Generated by Django 3.0 on 2020-09-14 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
            preserve_default=False,
        ),
    ]
