# Generated by Django 3.0 on 2020-09-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_cancellation_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
