# Generated by Django 3.0 on 2020-09-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_cancellation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='space_category',
        ),
        migrations.AddField(
            model_name='space',
            name='space_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.SpaceType'),
        ),
    ]
