# Generated by Django 3.0 on 2020-09-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20200915_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
