# Generated by Django 3.0 on 2020-09-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20200927_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='account_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='account_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='bank',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
