# Generated by Django 3.0 on 2020-09-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20200930_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='document',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
