# Generated by Django 3.0 on 2020-10-04 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_agent_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('billing_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_email', models.EmailField(max_length=254)),
                ('payment_cost', models.IntegerField()),
                ('payment_date', models.DateTimeField()),
                ('next_due_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi-annually', 'Bi-annually'), ('yearly', 'Yearly')], default='monthly', max_length=12)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPerAgent',
            fields=[
                ('sub_per_agent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurring', models.BooleanField(default=False)),
                ('next_due_date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subscription')),
            ],
        ),
    ]
