# Generated by Django 3.0 on 2020-10-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_billinghistory_subscription_subscriptionperagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionperagent',
            name='reference_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
