# Generated by Django 3.0 on 2020-10-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_subscriptionperagent_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionperagent',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Agent'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi-annually', 'Bi-annually'), ('yearly', 'Yearly')], default='monthly', max_length=12, unique=True),
        ),
    ]
