# Generated by Django 3.0 on 2020-10-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20201004_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionperagent',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
