# Generated by Django 3.0 on 2020-10-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_subscriptionperagent_authorization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_title',
            field=models.CharField(default='Package', max_length=50),
        ),
    ]
