# Generated by Django 3.0 on 2020-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_subscription_subscription_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionperagent',
            name='next_due_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
