# Generated by Django 3.0 on 2020-10-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20201004_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionperagent',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi-annually', 'Bi-annually'), ('yearly', 'Yearly'), ('per minute', 'Per Minute')], default='monthly', max_length=12, unique=True),
        ),
    ]
