# Generated by Django 3.0 on 2020-10-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20201004_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionperagent',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
