# Generated by Django 3.0 on 2020-10-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_subscriptionperagent_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
