# Generated by Django 3.0 on 2020-10-25 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_space_active'),
    ]
    def set_all_availabilities_space(apps, schema_editor):
        Availability = apps.get_model("api", "Availability")
        Space = apps.get_model("api", "Space")

        for availability in Availability.objects.all():
            space_name = availability.space
            space = Space.objects.filter(name=space_name).first()
            if space:
                availability.spaces = space
                availability.save()

    operations = [
        migrations.AddField(
            model_name='availability',
            name='spaces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Space'),
        ),
    ]
