# Generated by Django 3.0 on 2020-10-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20201025_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='space',
        ),
    ]
