# Generated by Django 3.0 on 2020-10-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_remove_availability_space'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='spaces',
            new_name='space',
        ),
    ]
