# Generated by Django 3.0 on 2020-10-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20201025_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='spaces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Space'),
        ),
    ]
