# Generated by Django 3.0 on 2020-10-25 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_extra_spaces'),
    ]

    def set_all_extras_space(apps, schema_editor):
        Extra = apps.get_model("api", "Extra")
        Space = apps.get_model("api", "Space")

        for extra in Extra.objects.all():
            space_name = extra.space
            space = Space.objects.filter(name=space_name).first()
            if space:
                extra.spaces = space
                extra.save()

    operations = [
        migrations.RunPython(set_all_extras_space,
                             migrations.RunPython.noop),
    ]
