# Generated by Django 3.0 on 2020-10-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20201025_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='space',
        ),
    ]
