# Generated by Django 3.0 on 2020-10-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_remove_extra_space'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='spaces',
            new_name='space',
        ),
    ]
