# Generated by Django 3.0 on 2020-11-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20201025_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
