# Generated by Django 3.0 on 2020-11-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20201117_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
