# Generated by Django 3.0 on 2020-12-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20201218_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
