# Generated by Django 3.0 on 2020-12-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20201227_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
