# Generated by Django 3.0 on 2020-12-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_user_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', max_length=12),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi-annually', 'Bi-annually'), ('yearly', 'Yearly'), ('per minute', 'Per Minute')], default='monthly', max_length=12),
        ),
    ]
