# Generated by Django 3.0 on 2020-12-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20201228_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_commission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
