# Generated by Django 3.0 on 2020-12-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20201230_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_commission',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_subscription',
        ),
        migrations.AddField(
            model_name='agent',
            name='plan',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('commission', 'Commission')], default='commission', max_length=50),
        ),
    ]
