# Generated by Django 3.0 on 2020-12-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20201230_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='plan',
            new_name='plans',
        ),
    ]
