# Generated by Django 3.0 on 2021-01-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20201230_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='duration',
        ),
    ]
