# Generated by Django 3.0 on 2021-01-17 02:45

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_remove_extra_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'image': 'image'}, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
