# Generated by Django 3.0 on 2021-01-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_space_image_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionperagent',
            name='reference_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
