# Generated by Django 3.0 on 2021-02-27 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20210117_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRules',
            fields=[
                ('cancellation_rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
            ],
        ),
    ]
