# Generated by Django 3.0 on 2021-03-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_cancellationrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
