# Generated by Django 3.0 on 2021-03-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20210304_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CancellationRules'),
        ),
    ]
