# Generated by Django 3.0 on 2021-03-14 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_order_cancellation_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='cancellation_rules',
        ),
        migrations.AddField(
            model_name='space',
            name='cancellation_rule',
            field=models.ForeignKey(default=uuid.UUID('4d87d4c2-c6ee-452d-a944-1d18f767c70d'), on_delete=django.db.models.deletion.CASCADE, to='api.CancellationRules'),
        ),
    ]
