# Generated by Django 3.0 on 2021-03-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20210314_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='cancellation_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CancellationRules'),
        ),
    ]
