# Generated by Django 3.0 on 2021-03-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_auto_20210314_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionperagent',
            options={'verbose_name_plural': 'Subscriptions per agent'},
        ),
    ]
