# Generated by Django 3.0 on 2021-04-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_auto_20210314_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'space host', 'verbose_name_plural': 'Space hosts'},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='billinghistory',
            options={'verbose_name_plural': 'Billing histories'},
        ),
        migrations.AlterModelOptions(
            name='cancellationrules',
            options={'verbose_name': 'cancellation rule', 'verbose_name_plural': 'Cancellation Rules'},
        ),
        migrations.AlterModelOptions(
            name='spacecategory',
            options={'verbose_name_plural': 'Space categories'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionperagent',
            options={'verbose_name': 'subscription per space host', 'verbose_name_plural': 'Subscriptions per space host'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='Space Host'),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='agent_email',
            field=models.EmailField(max_length=254, verbose_name='Space Host Email Address'),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='agent_name',
            field=models.CharField(max_length=50, verbose_name='Space Host'),
        ),
        migrations.AlterField(
            model_name='cancellation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agent', verbose_name='Space Host Business Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.CharField(default=' ', max_length=250, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='space',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agent', verbose_name='Space Host Business Name'),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SpaceType'),
        ),
        migrations.AlterField(
            model_name='subscriptionperagent',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Agent', verbose_name='Space Host Business Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='is space host'),
        ),
    ]
