# Generated by Django 3.0 on 2021-04-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20210418_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=None, max_length=250, on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='Customer'),
        ),
    ]
