# Generated by Django 3.0 on 2021-04-23 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20210422_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
    ]
