# Generated by Django 3.0 on 2021-04-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_rating_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.CharField(default=None, max_length=250, verbose_name='Customer'),
        ),
    ]
