# Generated by Django 3.0 on 2021-05-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20210423_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.order',),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='offline_booking',
            field=models.BooleanField(default=False),
        ),
    ]
