# Generated by Django 3.0 on 2021-05-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20210515_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineBooking',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.order',),
        ),
    ]
