# Generated by Django 3.0 on 2021-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_offlinebooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='agent',
            name='document_verified',
            field=models.BooleanField(default=False),
        ),
    ]
