# Generated by Django 3.0 on 2021-05-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20210523_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='document',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
