# Generated by Django 3.0 on 2021-06-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20210523_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='document',
            field=models.ImageField(default='default.png', upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
