# Generated by Django 3.0 on 2021-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20210620_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='document',
            field=models.FileField(default='default.png', upload_to='documents'),
        ),
    ]
